//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public long Id_Answers { get; set; }
        public long Id_TestResult { get; set; }
        public long Id_Question { get; set; }
        public byte AnswerNr { get; set; }
        public short Time { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual TestResult TestResult { get; set; }
    }
}
