//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit
    {
        public long Id_Audit { get; set; }
        public System.DateTime LoginTime { get; set; }
        public long Id_Person { get; set; }
        public bool LoginResult { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
