//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Survey.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Survey.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a new record!!.
        /// </summary>
        internal static string Error_Create {
            get {
                return ResourceManager.GetString("Error_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete record!!.
        /// </summary>
        internal static string Error_Delete {
            get {
                return ResourceManager.GetString("Error_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to process data!!.
        /// </summary>
        internal static string Error_Process {
            get {
                return ResourceManager.GetString("Error_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your input is too long!!.
        /// </summary>
        internal static string Error_TextTooLong {
            get {
                return ResourceManager.GetString("Error_TextTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your input is too short!!.
        /// </summary>
        internal static string Error_TextTooShort {
            get {
                return ResourceManager.GetString("Error_TextTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update record!!.
        /// </summary>
        internal static string Error_Update {
            get {
                return ResourceManager.GetString("Error_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New record created successfully!.
        /// </summary>
        internal static string Info_CreateSuccess {
            get {
                return ResourceManager.GetString("Info_CreateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record deleted successfully!.
        /// </summary>
        internal static string Info_DeleteSuccess {
            get {
                return ResourceManager.GetString("Info_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record updated successfully!.
        /// </summary>
        internal static string Info_UpdateSuccess {
            get {
                return ResourceManager.GetString("Info_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this record?.
        /// </summary>
        internal static string Warning_Delete {
            get {
                return ResourceManager.GetString("Warning_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select test first!.
        /// </summary>
        internal static string Warning_Select {
            get {
                return ResourceManager.GetString("Warning_Select", resourceCulture);
            }
        }
    }
}
